In [11]:
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
# text in Western (Windows 1252)

import numpy as np
import StringIO
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import regularizers
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.constraints import maxnorm
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.models import load_model
np.random.seed(7)

In [109]:
%run ../prepare_data.py

In [10]:
s = load_shuffle_vector('internal_representations/inputs/X_shuffled_part_shuffle_vector.h5')
s[0:3]

array([ 620791, 1893201, 1504314])

In [80]:
dictionary, max_word, max_num_vowels, content, vowels, accetuated_vowels = create_dict()

READING CONTENT...
CONTENT READ SUCCESSFULY
CREATING DICTIONARY...
DICTIONARY CREATION SUCCESSFUL!


In [111]:
generate_full_vowel_matrix_inputs('internal_representations/inputs/X_ordered_part', 6)
# dictionary, max_word, max_num_vowels, content, vowels, accetuated_vowels = create_dict()
# print('HERE!')
# num = count_vowels(content, vowels)
# print(num)

READING CONTENT...
CONTENT READ SUCCESSFULY
CREATING DICTIONARY...
DICTIONARY CREATION SUCCESSFUL!
GENERATING X AND y...
0
10000
20000
30000
40000
50000
60000
70000
80000
Saving part 1
90000
100000
110000
120000
130000
140000
150000
160000
170000
Saving part 2
180000
190000
200000
210000
220000
230000
240000
250000
260000
Saving part 3
270000
280000
290000
300000
310000
320000
330000
340000
350000
Saving part 4
360000
370000
380000
390000
400000
410000
420000
430000
440000
Saving part 5
450000
460000
470000
480000
490000
500000
510000
520000
530000
Saving part 6


In [128]:
h5f = h5py.File('internal_representations/inputs/X_ordered_part.h5','r')
# print h5f['X'][500000]
i = 799996
print decode_input(h5f['X'][i], dictionary)
print h5f['X_pure'][i]
print h5f['y'][i]
h5f.close()

# def decode_input(word_encoded, dictionary):
#     word = ''
#     for el in word_encoded:
#         i = 0
#         for num in el:
#             if num == 1:
#                 word += dictionary[i]
#                 break
#             i += 1
#     return word

nerazvitejših
0
1


In [110]:
h5f.close()
# h5f = h5py.File('internal_representations/inputs/X_ordered_part.h5', 'w')


ValueError: Not a file id (Not a file id)

In [ ]:
shuffle_full_vowel_inputs('internal_representations/inputs/X_shuffled_part', 'internal_representations/inputs/X_ordered_part', 6)

READING CONTENT...
CONTENT READ SUCCESSFULY
CREATING DICTIONARY...
DICTIONARY CREATION SUCCESSFUL!
Shuffled vector loaded!

In [17]:
X, y, X_pure = load_extended_inputs('internal_representations/inputs/X_ordered_part4.h5')

In [19]:
X[0]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [

In [34]:
s = StringIO.StringIO()
# np.savetxt(s, (1,2,3))
# s.getvalue()


with open("test.txt", "r") as text_file:
    s = StringIO.StringIO(text_file.read().replace(';', '\n'))

np.loadtxt(s, delimiter=',')

array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.],
       [

In [12]:
# X, y = generate_inputs()
# save_inputs('ordered_inputs.h5', X, y)
# X, y = load_inputs('ordered_inputs.h5')

# X, y = generate_matrix_inputs()
# save_inputs('ordered_matrix_inputs.h5', X, y)
# X, y = load_inputs('ordered_matrix_inputs.h5')

# X, y = generate_full_matrix_inputs()
# save_inputs('shuffeled_full_matrix_inputs.h5', X, y)
# X, y = load_inputs('shuffeled_full_matrix_inputs.h5')

X, y, X_pure = generate_full_vowel_matrix_inputs()

READING CONTENT...
CONTENT READ SUCCESSFULY
CREATING DICTIONARY...
DICTIONARY CREATION SUCCESSFUL!
1.85924481321
GENERATING X AND y...


MemoryError: 

In [4]:
X.shape

(536432, 23, 43)

In [ ]:
testX, testY = generate_full_vowel_matrix_inputs()

READING CONTENT...
CONTENT READ SUCCESSFULY
CREATING DICTIONARY...
DICTIONARY CREATION SUCCESSFUL!

In [5]:
# X = X[:100000]
# y = y[:100000]
# def unison_shuffled_copies(a, b):
#     assert len(a) == len(b)
#     p = np.random.permutation(len(a))
#     return a[p], b[p]
# X, y = unison_shuffled_copies(X, y)
# print X.shape

# train_X = X.astype(np.float32)
# train_y = y.astype(np.int32)

num_examples = len(X) # training set size
# nn_input_dim = max_word * len(dictionary) # input layer dimensionality
# nn_output_dim = max_num_vowels * max_num_vowels # output layer dimensionality
nn_output_dim = 121
nn_hdim = 516

# Gradient descent parameters (I picked these by hand)
# epsilon = 1 # learning rate for gradient descent
# reg_lambda = 1 # regularization strength

In [6]:
nn_output_dim

121

In [7]:
# model = Sequential()
# model.add(Conv2D(32, (3, 3), input_shape=(3, 32, 32), padding='same', activation='relu', kernel_constraint=maxnorm(3)))
# model.add(Dropout(0.2))
# model.add(Conv2D(32, (3, 3), activation='relu', padding='same', kernel_constraint=maxnorm(3)))
# model.add(MaxPooling2D(pool_size=(2, 2)))
# model.add(Flatten())
# model.add(Dense(512, activation='relu', kernel_constraint=maxnorm(3)))
# model.add(Dropout(0.5))
# model.add(Dense(num_classes, activation='softmax'))


np.random.seed(7)


# create model
# model = Sequential()
# model.add(Conv1D(43, (3), input_shape=(23, 43), padding='same', activation='relu'))
# model.add(Dropout(0.2))
# model.add(Conv1D(43, (3), padding='same', activation='relu'))
# model.add(MaxPooling1D(pool_size=2))
# model.add(Conv1D(86, (3), padding='same', activation='relu'))
# model.add(Dropout(0.2))
# model.add(Conv1D(86, (3), padding='same', activation='relu'))
# model.add(MaxPooling1D(pool_size=2))
# model.add(Conv1D(172, (3), padding='same', activation='relu'))
# model.add(Dropout(0.2))
# model.add(Conv1D(172, (3), padding='same', activation='relu'))
# model.add(MaxPooling1D(pool_size=2))
# # model.add(Conv1D(43, (3), input_shape=(None, 43), padding='same', activation='relu', kernel_constraint=maxnorm(3)))
# model.add(Flatten())
# model.add(Dense(1032, activation='relu', kernel_constraint=maxnorm(3)))
# model.add(Dropout(0.2))
# model.add(Dense(516, activation='relu', kernel_constraint=maxnorm(3)))
# model.add(Dropout(0.2))
# model.add(Dense(nn_output_dim, activation='softmax'))


# create model
model = Sequential()
model.add(Conv1D(43, (3), input_shape=(23, 43), padding='same', activation='relu'))
model.add(Dropout(0.2))
model.add(Conv1D(43, (3), padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=2))
# model.add(Conv1D(43, (3), input_shape=(None, 43), padding='same', activation='relu', kernel_constraint=maxnorm(3)))
model.add(Flatten())
# model.add(Dense(1032, activation='relu', kernel_constraint=maxnorm(3)))
# model.add(Dropout(0.2))
model.add(Dense(516, activation='relu', kernel_constraint=maxnorm(3)))
model.add(Dropout(0.2))
model.add(Dense(nn_output_dim, activation='sigmoid'))

In [8]:
epochs = 5
lrate = 0.1
decay = lrate/epochs
sgd = SGD(lr=lrate, momentum=0.9, decay=decay, nesterov=False)
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

# Compile model
# model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [12]:
# model.fit_generator((X, y), 536432/2, epochs=5)
# testX = X[:536432/16]
# print testX.shape
# testY = y[:536432/16]
# print testY.shape
model.fit(X[:429145], y[:429145], epochs=5, batch_size=10)
# model.fit(X, y, epochs=5, validation_split=0.2, batch_size=10)

Epoch 1/5
429145/429145 [==============================] - 1474s - loss: 8.9041e-04 - acc: 0.9352  
Epoch 2/5
429145/429145 [==============================] - 1515s - loss: 8.6358e-04 - acc: 0.9371  
Epoch 3/5
429145/429145 [==============================] - 1578s - loss: 8.4486e-04 - acc: 0.9392  
Epoch 4/5
429145/429145 [==============================] - 1566s - loss: 8.3320e-04 - acc: 0.9396  
Epoch 5/5
429145/429145 [==============================] - 1595s - loss: 8.1393e-04 - acc: 0.9416  


In [14]:
model.save('cnn_i2_s_c43-3relu_d20_c43-3relu_mp2_f_516relu_d20_121sigmoid_mse_adam_a65_10epoch.h5')

In [5]:
model = load_model('cnn_i2_s_c43-3relu_d20_c43-3relu_mp2_f_516relu_d20_121sigmoid_mse_adam_a65.h5')

In [13]:
# evaluate the model
scores = model.evaluate(X[429145:], y[429145:])
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

107232/107287 [============================>.] - ETA: 0s
acc: 96.52%


In [118]:
# calculate predictions
# test = generate_input_from_word('test', max_word, dictionary)
# print test.shape
# print test.T.shape
predictions = model.predict(np.array([generate_input_from_word('biotski', max_word, dictionary)]))
# round predictions

print decode_position(predictions[0], max_num_vowels)

b_pred = 0
ind = 0
i = 0
for el in predictions[0]:
    if b_pred < el:
        b_pred = el
        ind = i
    i += 1
    
print(ind)
# rounded = [round(x[0]) for x in predictions]
# print(rounded)

[2, 0]
2


In [12]:
print max_num_vowels

11


In [21]:
dictionary, max_word, max_num_vowels, content, vowels, accetuated_vowels = create_dict()
def generate_input_from_word(word, max_word, dictionary):
    x = np.zeros((max_word, len(dictionary)))
    j = 0
    for c in list(word):
        index = 0
        for d in dictionary:
            if c == d:
                x[j, index] = 1
                break
            index += 1
        j += 1
    return x

# model = load_model()
# prediction = predict(model, generate_input_from_word('hidrija'))
# print decode_position(prediction[0])

READING CONTENT...
CONTENT READ SUCCESSFULY
CREATING DICTIONARY...
DICTIONARY CREATION SUCCESSFUL!
