In [4]:
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
# text in Western (Windows 1252)

import pickle
import numpy as np
# import StringIO
import math
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, BaggingClassifier
from skmultilearn.problem_transform.br import BinaryRelevance
from scipy import sparse
import gc


# from keras import backend as Input
np.random.seed(7)

In [2]:
#%run ../../../prepare_data.py

import sys
sys.path.insert(0, '../../../')
from prepare_data import *

Using Theano backend.


In [15]:
%run ../../../prepare_data.py

mode = 'l'


data = Data(mode)
if mode == 'l':
    data.generate_data('../../internal_representations/inputs/letters_word_accentuation_train',
                       '../../internal_representations/inputs/letters_word_accentuation_test',
                       '../../internal_representations/inputs/letters_word_accentuation_validate')
else:
    data.generate_data('../../internal_representations/inputs/syllables_word_accetuation_train',
                       '../../internal_representations/inputs/syllables_word_accetuation_test',
                       '../../internal_representations/inputs/syllables_word_accetuation_validate')

LOADING DATA...
LOAD SUCCESSFUL!


In [16]:
content = data._read_content('../../../data/SlovarIJS_BESEDE_utf8.lex')
dictionary, max_word, max_num_vowels, vowels, accented_vowels = data._create_dict(content)
feature_dictionary = data._create_feature_dictionary()
syllable_dictionary = data._create_syllables_dictionary(content, vowels)

In [6]:
print(data.x_train.shape)
print(data.x_train[0])

(430151, 10)
[4738 1873    2 1677 1226 2130    0    0    0    0]


In [6]:
filename = 'test_dump_train'
pickle.dump(reshaped_train, open(filename, 'wb'))
filename = 'test_dump_test'
pickle.dump(data.y_train, open(filename, 'wb'))

In [3]:
filename = 'test_dump_train'
reshaped_train = pickle.load(open(filename, 'rb'))
filename = 'test_dump_test'
y_train = pickle.load(open(filename, 'rb'))

FileNotFoundError: [Errno 2] No such file or directory: 'test_dump_train'

In [4]:
# print (X_train.shape)
# print (X_test.shape)
# print (X_validate.shape)
pos = 0
# print (decode_input(X_train[pos], dictionary))
# print (decode_X_features(feature_dictionary, [X_other_features_train[pos]]))
# print(decode_position(y_train[pos]))
# print('------------------------------------')

print (data.x_train.shape)
print (data.x_train[0])
#test = [np.reshape(data.x_train[i], 828) for i in range(data.x_train.shape[0])]
#test = np.reshape(data.x_train[0], 23 * 36)
#print(test[0])
#print(test[0])
reshaped_train = np.reshape(data.x_train, (data.x_train.shape[0], 828))
reshaped_train = sparse.csr_matrix(reshaped_train)
del(data.x_train)
gc.collect()

print(reshaped_train.shape)
print(reshaped_train[1])
print (data.x_other_features_train.shape)
final_train = np.concatenate((reshaped_train, data.x_other_features_train), axis=1)
final_train = sparse.csr_matrix(final_train)
print(final_train.shape)
def reshape_set(s, size):
    return np.reshape(s, (size, 828))

430151 * 828

(430151, 23, 36)
[[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 

ValueError: zero-dimensional arrays cannot be concatenated

In [5]:
print (data.y_train.shape)

(430151, 10)


In [5]:
svm = LinearSVC(random_state=0)
cls = BinaryRelevance(classifier=svm)

#cls.fit(reshaped_train, data.y_train)
cls.fit(reshaped_train, y_train)

MemoryError: 

In [5]:
reshaped_test = np.reshape(data.x_test, (data.x_test.shape[0], 828))

for i in range(-5, 5):
    val = math.pow(10, i)
    filename = 'finalized_model_c_' + str(val) + '.sav'
    cls = pickle.load(open(filename, 'rb'))

    result = cls.score(reshaped_test, data.y_test)
    print(val)
    print(result)

1e-05
0.554266395175
0.0001
0.611394982519
0.001
0.626954550693
0.01
0.629240462561
0.1
0.629278881248
1.0
0.629931998924
10.0
0.62906757847


FileNotFoundError: [Errno 2] No such file or directory: 'finalized_model_c_100.0.sav'

In [5]:
reshaped_test = np.reshape(data.x_test, (data.x_test.shape[0], 828))

for i in range(-5, 5):
    val = math.pow(10, i)
    filename = 'finalized_model_c_balanced_' + str(val) + '.sav'
    cls = pickle.load(open(filename, 'rb'))

    result = cls.score(reshaped_test, data.y_test)
    print(val)
    print(result)

1e-05
0.377290714203
0.0001
0.427427100542
0.001
0.45159245457
0.01
0.45731683891
0.1
0.457816281839
1.0
0.457624188405
10.0
0.461542894464
100.0
0.553056206539
1000.0
0.523761957816


FileNotFoundError: [Errno 2] No such file or directory: 'finalized_model_c_balanced_10000.0.sav'

In [3]:
filename = 'data/letters_word_accentuation_x_train.pkl'
x_train = pickle.load(open(filename, 'rb'))
filename = 'data/letters_word_accentuation_x_test.pkl'
x_test = pickle.load(open(filename, 'rb'))
filename = 'data/letters_word_accentuation_y_train.pkl'
y_train = pickle.load(open(filename, 'rb'))
filename = 'data/letters_word_accentuation_y_test.pkl'
y_test = pickle.load(open(filename, 'rb'))

In [ ]:
# BaggingClassifier


rf = BaggingClassifier(random_state=0)
cls = BinaryRelevance(classifier=rf)

#cls.fit(reshaped_train, data.y_train)
cls.fit(x_train, y_train)

In [ ]:
result = cls.score(x_test, y_test)
print(result)

In [6]:
# AdaBoostClassifier, BaggingClassifier


rf = AdaBoostClassifier(random_state=0)
cls = BinaryRelevance(classifier=rf)

#cls.fit(reshaped_train, data.y_train)
cls.fit(x_train, y_train)

BinaryRelevance(classifier=AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=0),
        require_dense=[True, True])

In [ ]:
result = cls.score(x_test, y_test)
print(result)

In [7]:
# RANDOM FOREST

rf = RandomForestClassifier(random_state=0, verbose=True)
cls = BinaryRelevance(classifier=rf)

#cls.fit(reshaped_train, data.y_train)
cls.fit(x_train, y_train)

[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:   34.2s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:   43.6s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:   40.5s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:   41.4s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:   48.9s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:   45.4s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:   47.0s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:   34.4s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:   26.3s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.9s finished


BinaryRelevance(classifier=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=True,
            warm_start=False),
        require_dense=[True, True])

In [8]:
result = cls.score(x_test, y_test)
print(result)

[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.3s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.1s finished


0.785009028391


[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.0s finished


In [29]:
res = cls.predict_proba(x_test)
#for i in range(50):
#    print(data.decode_x(data.x_test[i], dictionary)[::-1])
predicts = res.toarray()

[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.3s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.3s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.0s finished


In [31]:
accuracy, errors = data.test_accuracy(predicts, data.x_test, data.x_other_features_test, data.y_test, dictionary, feature_dictionary, vowels, syllable_dictionary=syllable_dictionary)

In [33]:
output = open('rf_errors.pkl', 'wb')
pickle.dump(errors, output)
output.close()
output = open('rf_predictions.pkl', 'wb')
pickle.dump(predicts, output)
output.close()

In [15]:
# reshaped_test = np.reshape(data.x_test, (data.x_test.shape[0], 828))

filename = 'data/letters_word_accentuation_x_test.pkl'
x_test = pickle.load(open(filename, 'rb'))
filename = 'data/letters_word_accentuation_y_test.pkl'
y_test = pickle.load(open(filename, 'rb'))
filename = 'complete_input.sav'
cls = pickle.load(open(filename, 'rb'))

result = cls.score(x_test, y_test)
print(result)

0.641227092858


In [22]:
for i in range(10):
    print (data.decode_x(data.x_test[i], dictionary))
result.todense()


akbig
hinjovop
olitsupod
ovokinevtsnanz
vetižorobo
menazaman
miničiramčrk
avivajop
ivijlovodaz
menhidv


matrix([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])