In [1]:
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
# text in Western (Windows 1252)

import pickle
import numpy as np
# import StringIO
import math
from skmultilearn.problem_transform.br import BinaryRelevance
from sklearn.svm import LinearSVC

# from keras import backend as Input
np.random.seed(7)

ImportError: No module named builtins

In [2]:
#%run ../../../prepare_data.py

import sys
sys.path.insert(0, '../../../')
from prepare_data import *

Using Theano backend.


In [3]:
%run ../../../prepare_data.py
# X_train, X_other_features_train, y_train, X_test, X_other_features_test, y_test, X_validate, X_other_features_validate, y_validate = generate_full_matrix_inputs('../../internal_representations/inputs/content_shuffle_vector.h5', '../../internal_representations/inputs/shuffle_vector')
# save_inputs('../../internal_representations/inputs/shuffled_letters_train.h5', X_train, y_train, other_features = X_other_features_train)
# save_inputs('../../internal_representations/inputs/shuffled_letters_test.h5', X_test, y_test, other_features = X_other_features_test)
# save_inputs('../../internal_representations/inputs/shuffled_letters_validate.h5', X_validate, y_validate,  other_features = X_other_features_validate)
# X_train, X_other_features_train, y_train = load_inputs('../../internal_representations/inputs/shuffled_letters_train.h5', other_features=True)
# X_test, X_other_features_test, y_test = load_inputs('../../internal_representations/inputs/shuffled_letters_test.h5', other_features=True)
# X_validate, X_other_features_validate, y_validate = load_inputs('../../internal_representations/inputs/shuffled_letters_validate.h5', other_features=True)

data = Data('l')
#data.generate_data('../../internal_representations/inputs/letters_word_accentuation_train_TEST',
#                   '../../internal_representations/inputs/letters_word_accentuation_test_TEST',
#                   '../../internal_representations/inputs/letters_word_accentuation_validate_TEST')
#data.generate_data('../../internal_representations/inputs/letters_word_accentuation_train_TEST2',
#                   '../../internal_representations/inputs/letters_word_accentuation_test_TEST2',
#                   '../../internal_representations/inputs/letters_word_accentuation_validate_TEST2')
#data.generate_data('../../internal_representations/inputs/letters_word_accentuation_train_TEST_UNSHUFLED',
#                   '../../internal_representations/inputs/letters_word_accentuation_test_TEST_UNSHUFLED',
#                   '../../internal_representations/inputs/letters_word_accentuation_validate_TEST_UNSHUFLED')
data.generate_data('../../internal_representations/inputs/letters_word_accentuation_train',
                   '../../internal_representations/inputs/letters_word_accentuation_test',
                   '../../internal_representations/inputs/letters_word_accentuation_validate')

LOADING DATA...
LOAD SUCCESSFUL!


In [4]:
# print (X_train.shape)
# print (X_test.shape)
# print (X_validate.shape)
pos = 0
# print (decode_input(X_train[pos], dictionary))
# print (decode_X_features(feature_dictionary, [X_other_features_train[pos]]))
# print(decode_position(y_train[pos]))
# print('------------------------------------')

print (data.x_train[0].shape)
print (data.x_train[0])
#test = [np.reshape(data.x_train[i], 828) for i in range(data.x_train.shape[0])]
#test = np.reshape(data.x_train[0], 23 * 36)
#print(test[0])
#print(test[0])
reshaped_train = np.reshape(data.x_train, (data.x_train.shape[0], 828))
print(reshaped_train[0])

(23, 36)
[[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 

In [5]:
print (data.y_train.shape)

(430151, 10)


In [7]:
svm = LinearSVC(random_state=0)
cls = BinaryRelevance(classifier=svm)

cls.fit(reshaped_train, data.y_train)

NameError: name 'BinaryRelevance' is not defined

In [43]:
gen = data.generator('validate', batch_size)

In [44]:
test = gen.__next__()

In [67]:
print(test[0][0].shape)
print(test[0][1].shape)
print(test[0][2].shape)
#print(np.hsplit(test[0][0], 2)[0][0])
#print(np.hsplit(test[0][0], 2)[1][0])

(16, 23, 36)
(16, 23, 36)
(54222, 140)


In [4]:
data.x_train = np.concatenate((data.x_train, data.x_test, data.x_validate), axis=0)
data.x_other_features_train = np.concatenate((data.x_other_features_train, data.x_other_features_test, data.x_other_features_validate), axis=0)
data.y_train = np.concatenate((data.y_train, data.y_test, data.y_validate), axis=0)

In [4]:
data.x_train = None
data.x_other_features_train = None
data.y_train = None

In [5]:
num_examples = 54222 # training set size
# num_examples = len(data.x_train)  # training set size
nn_output_dim = 10
nn_hdim = 516
batch_size = 16
actual_epoch = 20
num_fake_epoch = 20




conv_input_shape=(23, 36)
othr_input = (140, )

conv_input = Input(shape=conv_input_shape, name='conv_input')
x_conv = Conv1D(115, (3), padding='same', activation='relu')(conv_input)
x_conv = Conv1D(46, (3), padding='same', activation='relu')(x_conv)
x_conv = MaxPooling1D(pool_size=2)(x_conv)
x_conv = Flatten()(x_conv)
# x_conv = Dense(516, activation='relu', kernel_constraint=maxnorm(3))(x_conv)

conv_input2 = Input(shape=conv_input_shape, name='conv_input2')
x_conv2 = Conv1D(115, (3), padding='same', activation='relu')(conv_input2)
x_conv2 = Conv1D(46, (3), padding='same', activation='relu')(x_conv2)
x_conv2 = MaxPooling1D(pool_size=2)(x_conv2)
x_conv2 = Flatten()(x_conv2)
# x_conv = Dense(516, activation='relu', kernel_constraint=maxnorm(3))(x_conv)

othr_input = Input(shape=othr_input, name='othr_input')
# x_othr = Dense(256, input_dim=167, activation='relu')(othr_input)
# x_othr = Dropout(0.3)(x_othr)
# x_othr = Dense(512, activation='relu')(othr_input)
# x_othr = Dropout(0.3)(x_othr)
# x_othr = Dense(256, activation='relu')(othr_input)

#x1 = concatenate([x_conv, x_conv2])
#x = concatenate([x1, othr_input])

x = concatenate([x_conv, x_conv2, othr_input])
# x = Dense(1024, input_dim=(516 + 256), activation='relu')(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.3)(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.3)(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.3)(x)
x = Dense(nn_output_dim, activation='sigmoid')(x)




model = Model(inputs=[conv_input, conv_input2, othr_input], outputs=x)
opt = optimizers.Adam(lr=1E-3, beta_1=0.9, beta_2=0.999, epsilon=1e-08)
model.compile(loss='mean_squared_error', optimizer=opt, metrics=[actual_accuracy,])
# model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [ ]:
history = model.fit_generator(data.generator('validate', batch_size), 
                              data.x_validate.shape[0]/(batch_size * num_fake_epoch), 
                              epochs=actual_epoch*num_fake_epoch, 
                              validation_data=data.generator('test', batch_size), 
                              validation_steps=data.x_test.shape[0]/(batch_size * num_fake_epoch))

Epoch 1/400
170/169 [==============================] - 4s - loss: 0.0748 - actual_accuracy: 0.3026 - val_loss: 0.0542 - val_actual_accuracy: 0.5533
Epoch 2/400
170/169 [==============================] - 4s - loss: 0.0515 - actual_accuracy: 0.5673 - val_loss: 0.0472 - val_actual_accuracy: 0.6415
Epoch 3/400
170/169 [==============================] - 5s - loss: 0.0449 - actual_accuracy: 0.6327 - val_loss: 0.0446 - val_actual_accuracy: 0.6526
Epoch 4/400
170/169 [==============================] - 5s - loss: 0.0414 - actual_accuracy: 0.6665 - val_loss: 0.0426 - val_actual_accuracy: 0.6718
Epoch 5/400
170/169 [==============================] - 7s - loss: 0.0367 - actual_accuracy: 0.7037 - val_loss: 0.0415 - val_actual_accuracy: 0.6825
Epoch 6/400
170/169 [==============================] - 7s - loss: 0.0332 - actual_accuracy: 0.7346 - val_loss: 0.0485 - val_actual_accuracy: 0.6545
Epoch 7/400
170/169 [==============================] - 7s - loss: 0.0283 - actual_accuracy: 0.7820 - val_loss: 0

In [6]:
name = '20_final_epoch'
model.save(name + '.h5')
output = open(name + '_history.pkl', 'wb')
pickle.dump(history.history, output)
output.close()

In [5]:
#data = Data('l')
content = data._read_content('../../../data/SlovarIJS_BESEDE_utf8.lex')
dictionary, max_word, max_num_vowels, vowels, accented_vowels = data._create_dict(content)
feature_dictionary = data._create_feature_dictionary()

In [9]:
# PREDICT TEST DATA!!!
predictions = model.predict_generator(data.generator('validate', batch_size, content_name='SlovarIJS_BESEDE_utf8.lex'), 
                                      data.x_validate.shape[0]/(batch_size))

In [12]:
accuracy, errors = data.test_accuracy(predictions, data.x_validate, data.x_other_features_validate, data.y_validate, dictionary, feature_dictionary, vowels)

In [18]:
errors

[[33994, 'adamovega', 'Aspnsg-', 'adámovega', 'ádamovega'],
 [7182, 'adamovem', 'Aspnsl-', 'adámovem', 'ádamovem'],
 [18764, 'adamovemu', 'Aspnsd-', 'adámovemu', 'ádamovemu'],
 [25599, 'adamovim', 'Aspnsi-', 'adámovim', 'ádamovim'],
 [37104, 'adamovo', 'Aspnsn-', 'adámovo', 'ádamovo'],
 [43994, 'adamovo', 'Aspnsa-', 'adámovo', 'ádamovo'],
 [20031, 'algastemu', 'Agpmsd-', 'álgástemu', 'álgastemu'],
 [39855, 'alkoholika', 'Ncmsay', 'alkóhólika', 'alkohólika'],
 [23437, 'alkoholikov', 'Ncmpg-', 'alkoholikov', 'alkohólikov'],
 [35909, 'alkoholikov', 'Ncmdg-', 'alkoholikov', 'alkohólikov'],
 [5063, 'amater', 'Ncmsn-', 'amáter', 'amatér'],
 [4727, 'amaterja', 'Ncmsg-', 'amáterja', 'amatérja'],
 [7503, 'amaterja', 'Ncmda-', 'amáterja', 'amatérja'],
 [20420, 'amaterja', 'Ncmsay', 'amáterja', 'amatérja'],
 [42093, 'amaterja', 'Ncmdn-', 'amáterja', 'amatérja'],
 [52119, 'amaterje', 'Ncmpa-', 'amáterje', 'amatérje'],
 [5484, 'amaterjem', 'Ncmpd-', 'amáterjem', 'amatérjem'],
 [7576, 'amaterjem', '

In [17]:
errors.sort(key=lambda x: x[1])

In [15]:
errors = [[el[0], el[1][::-1], el[2], el[3][::-1], el[4][::-1]] for el in errors]