In [11]:
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
# text in Western (Windows 1252)

import pickle
import numpy as np
# import StringIO
import math
from sklearn.svm import LinearSVC
from skmultilearn.problem_transform.br import BinaryRelevance
from scipy import sparse
import gc


# from keras import backend as Input
np.random.seed(7)

In [2]:
#%run ../../../prepare_data.py

import sys
sys.path.insert(0, '../../../')
from prepare_data import *

Using Theano backend.


In [3]:
%run ../../../prepare_data.py

mode = 'l'


data = Data(mode)
if mode == 'l':
    data.generate_data('../../internal_representations/inputs/letters_word_accentuation_train',
                       '../../internal_representations/inputs/letters_word_accentuation_test',
                       '../../internal_representations/inputs/letters_word_accentuation_validate')
else:
    data.generate_data('../../internal_representations/inputs/syllables_word_accetuation_train',
                       '../../internal_representations/inputs/syllables_word_accetuation_test',
                       '../../internal_representations/inputs/syllables_word_accetuation_validate')

LOADING DATA...
LOAD SUCCESSFUL!


In [7]:
content = data._read_content('../../../data/SlovarIJS_BESEDE_utf8.lex')
dictionary, max_word, max_num_vowels, vowels, accented_vowels = data._create_dict(content)
feature_dictionary = data._create_feature_dictionary()
syllable_dictionary = data._create_syllables_dictionary(content, vowels)

In [6]:
print(data.x_train.shape)
print(data.x_train[0])

(430151, 10)
[4738 1873    2 1677 1226 2130    0    0    0    0]


In [6]:
filename = 'test_dump_train'
pickle.dump(reshaped_train, open(filename, 'wb'))
filename = 'test_dump_test'
pickle.dump(data.y_train, open(filename, 'wb'))

In [4]:
filename = 'test_dump_train'
reshaped_train = pickle.load(open(filename, 'rb'))
filename = 'test_dump_test'
y_train = pickle.load(open(filename, 'rb'))

In [4]:
# print (X_train.shape)
# print (X_test.shape)
# print (X_validate.shape)
pos = 0
# print (decode_input(X_train[pos], dictionary))
# print (decode_X_features(feature_dictionary, [X_other_features_train[pos]]))
# print(decode_position(y_train[pos]))
# print('------------------------------------')

print (data.x_train.shape)
print (data.x_train[0])
#test = [np.reshape(data.x_train[i], 828) for i in range(data.x_train.shape[0])]
#test = np.reshape(data.x_train[0], 23 * 36)
#print(test[0])
#print(test[0])
reshaped_train = np.reshape(data.x_train, (data.x_train.shape[0], 828))
reshaped_train = sparse.csr_matrix(reshaped_train)
del(data.x_train)
gc.collect()

print(reshaped_train.shape)
print(reshaped_train[1])
print (data.x_other_features_train.shape)
final_train = np.concatenate((reshaped_train, data.x_other_features_train), axis=1)
final_train = sparse.csr_matrix(final_train)
print(final_train.shape)
def reshape_set(s, size):
    return np.reshape(s, (size, 828))

430151 * 828

(430151, 23, 36)
[[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 

ValueError: zero-dimensional arrays cannot be concatenated

  (0, 3)	1
  (0, 30)	1
  (0, 51)	1
  (0, 67)	1
  (0, 68)	1
  (0, 79)	1
  (0, 102)	1
  (0, 120)	1
  (0, 139)	1
  (0, 140)	1
  (0, 160)	1
  (0, 175)	1
  (0, 176)	1
  (0, 183)	1
  (0, 210)	1
  (0, 239)	1
  (0, 247)	1
  (0, 248)	1
  (0, 259)	1
  (0, 282)	1
  (0, 300)	1
  (0, 319)	1
  (0, 320)	1
  (0, 341)	1
  (0, 354)	1
  (0, 364)	1
  (0, 391)	1
  (0, 393)	1
  (0, 394)	1


In [5]:
print (data.y_train.shape)

(430151, 10)


In [5]:
svm = LinearSVC(random_state=0)
cls = BinaryRelevance(classifier=svm)

#cls.fit(reshaped_train, data.y_train)
cls.fit(reshaped_train, y_train)

MemoryError: 

In [5]:
reshaped_test = np.reshape(data.x_test, (data.x_test.shape[0], 828))

for i in range(-5, 5):
    val = math.pow(10, i)
    filename = 'finalized_model_c_' + str(val) + '.sav'
    cls = pickle.load(open(filename, 'rb'))

    result = cls.score(reshaped_test, data.y_test)
    print(val)
    print(result)

1e-05
0.554266395175
0.0001
0.611394982519
0.001
0.626954550693
0.01
0.629240462561
0.1
0.629278881248
1.0
0.629931998924
10.0
0.62906757847


FileNotFoundError: [Errno 2] No such file or directory: 'finalized_model_c_100.0.sav'

In [5]:
reshaped_test = np.reshape(data.x_test, (data.x_test.shape[0], 828))

for i in range(-5, 5):
    val = math.pow(10, i)
    filename = 'finalized_model_c_balanced_' + str(val) + '.sav'
    cls = pickle.load(open(filename, 'rb'))

    result = cls.score(reshaped_test, data.y_test)
    print(val)
    print(result)

1e-05
0.377290714203
0.0001
0.427427100542
0.001
0.45159245457
0.01
0.45731683891
0.1
0.457816281839
1.0
0.457624188405
10.0
0.461542894464
100.0
0.553056206539
1000.0
0.523761957816


FileNotFoundError: [Errno 2] No such file or directory: 'finalized_model_c_balanced_10000.0.sav'

In [12]:
filename = 'data/letters_word_accentuation_x_train.pkl'
x_train = pickle.load(open(filename, 'rb'))
filename = 'data/letters_word_accentuation_x_test.pkl'
x_test = pickle.load(open(filename, 'rb'))
filename = 'data/letters_word_accentuation_y_train.pkl'
y_train = pickle.load(open(filename, 'rb'))
filename = 'data/letters_word_accentuation_y_test.pkl'
y_test = pickle.load(open(filename, 'rb'))

In [15]:
# reshaped_test = np.reshape(data.x_test, (data.x_test.shape[0], 828))

filename = 'data/letters_word_accentuation_x_test.pkl'
x_test = pickle.load(open(filename, 'rb'))
filename = 'data/letters_word_accentuation_y_test.pkl'
y_test = pickle.load(open(filename, 'rb'))
filename = 'complete_input.sav'
cls = pickle.load(open(filename, 'rb'))

result = cls.score(x_test, y_test)
print(result)

0.641227092858


In [6]:
#data = Data('l')
content = data._read_content('../../../data/SlovarIJS_BESEDE_utf8.lex')
dictionary, max_word, max_num_vowels, vowels, accented_vowels = data._create_dict(content)
feature_dictionary = data._create_feature_dictionary()

In [8]:

#print(reshape_set(data.x_test[pos], 1))
test_examples = reshape_set(data.x_test[:10], 10)

akbig
[[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0
  0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 

In [19]:
filename = 'finalized_model_c_1.0.sav'
cls = pickle.load(open(filename, 'rb'))
result = cls.predict(test_examples)
print(result)

  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (4, 1)	1.0
  (5, 1)	1.0
  (7, 1)	1.0
  (8, 1)	1.0
  (9, 1)	1.0
  (3, 2)	1.0
  (5, 2)	1.0
  (3, 3)	1.0
  (3, 4)	1.0


In [22]:
for i in range(10):
    print (data.decode_x(data.x_test[i], dictionary))
result.todense()


akbig
hinjovop
olitsupod
ovokinevtsnanz
vetižorobo
menazaman
miničiramčrk
avivajop
ivijlovodaz
menhidv


matrix([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [17]:
data.y_test.shape

(52058, 10)

In [43]:
gen = data.generator('validate', batch_size)

In [44]:
test = gen.__next__()

In [67]:
print(test[0][0].shape)
print(test[0][1].shape)
print(test[0][2].shape)
#print(np.hsplit(test[0][0], 2)[0][0])
#print(np.hsplit(test[0][0], 2)[1][0])

(16, 23, 36)
(16, 23, 36)
(54222, 140)


In [4]:
data.x_train = np.concatenate((data.x_train, data.x_test, data.x_validate), axis=0)
data.x_other_features_train = np.concatenate((data.x_other_features_train, data.x_other_features_test, data.x_other_features_validate), axis=0)
data.y_train = np.concatenate((data.y_train, data.y_test, data.y_validate), axis=0)

In [4]:
data.x_train = None
data.x_other_features_train = None
data.y_train = None

In [5]:
num_examples = 54222 # training set size
# num_examples = len(data.x_train)  # training set size
nn_output_dim = 10
nn_hdim = 516
batch_size = 16
actual_epoch = 20
num_fake_epoch = 20




conv_input_shape=(23, 36)
othr_input = (140, )

conv_input = Input(shape=conv_input_shape, name='conv_input')
x_conv = Conv1D(115, (3), padding='same', activation='relu')(conv_input)
x_conv = Conv1D(46, (3), padding='same', activation='relu')(x_conv)
x_conv = MaxPooling1D(pool_size=2)(x_conv)
x_conv = Flatten()(x_conv)
# x_conv = Dense(516, activation='relu', kernel_constraint=maxnorm(3))(x_conv)

conv_input2 = Input(shape=conv_input_shape, name='conv_input2')
x_conv2 = Conv1D(115, (3), padding='same', activation='relu')(conv_input2)
x_conv2 = Conv1D(46, (3), padding='same', activation='relu')(x_conv2)
x_conv2 = MaxPooling1D(pool_size=2)(x_conv2)
x_conv2 = Flatten()(x_conv2)
# x_conv = Dense(516, activation='relu', kernel_constraint=maxnorm(3))(x_conv)

othr_input = Input(shape=othr_input, name='othr_input')
# x_othr = Dense(256, input_dim=167, activation='relu')(othr_input)
# x_othr = Dropout(0.3)(x_othr)
# x_othr = Dense(512, activation='relu')(othr_input)
# x_othr = Dropout(0.3)(x_othr)
# x_othr = Dense(256, activation='relu')(othr_input)

#x1 = concatenate([x_conv, x_conv2])
#x = concatenate([x1, othr_input])

x = concatenate([x_conv, x_conv2, othr_input])
# x = Dense(1024, input_dim=(516 + 256), activation='relu')(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.3)(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.3)(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.3)(x)
x = Dense(nn_output_dim, activation='sigmoid')(x)




model = Model(inputs=[conv_input, conv_input2, othr_input], outputs=x)
opt = optimizers.Adam(lr=1E-3, beta_1=0.9, beta_2=0.999, epsilon=1e-08)
model.compile(loss='mean_squared_error', optimizer=opt, metrics=[actual_accuracy,])
# model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [ ]:
history = model.fit_generator(data.generator('validate', batch_size), 
                              data.x_validate.shape[0]/(batch_size * num_fake_epoch), 
                              epochs=actual_epoch*num_fake_epoch, 
                              validation_data=data.generator('test', batch_size), 
                              validation_steps=data.x_test.shape[0]/(batch_size * num_fake_epoch))

Epoch 1/400
170/169 [==============================] - 4s - loss: 0.0748 - actual_accuracy: 0.3026 - val_loss: 0.0542 - val_actual_accuracy: 0.5533
Epoch 2/400
170/169 [==============================] - 4s - loss: 0.0515 - actual_accuracy: 0.5673 - val_loss: 0.0472 - val_actual_accuracy: 0.6415
Epoch 3/400
170/169 [==============================] - 5s - loss: 0.0449 - actual_accuracy: 0.6327 - val_loss: 0.0446 - val_actual_accuracy: 0.6526
Epoch 4/400
170/169 [==============================] - 5s - loss: 0.0414 - actual_accuracy: 0.6665 - val_loss: 0.0426 - val_actual_accuracy: 0.6718
Epoch 5/400
170/169 [==============================] - 7s - loss: 0.0367 - actual_accuracy: 0.7037 - val_loss: 0.0415 - val_actual_accuracy: 0.6825
Epoch 6/400
170/169 [==============================] - 7s - loss: 0.0332 - actual_accuracy: 0.7346 - val_loss: 0.0485 - val_actual_accuracy: 0.6545
Epoch 7/400
170/169 [==============================] - 7s - loss: 0.0283 - actual_accuracy: 0.7820 - val_loss: 0

In [6]:
name = '20_final_epoch'
model.save(name + '.h5')
output = open(name + '_history.pkl', 'wb')
pickle.dump(history.history, output)
output.close()

In [5]:
#data = Data('l')
content = data._read_content('../../../data/SlovarIJS_BESEDE_utf8.lex')
dictionary, max_word, max_num_vowels, vowels, accented_vowels = data._create_dict(content)
feature_dictionary = data._create_feature_dictionary()

In [9]:
# PREDICT TEST DATA!!!
predictions = model.predict_generator(data.generator('validate', batch_size, content_name='SlovarIJS_BESEDE_utf8.lex'), 
                                      data.x_validate.shape[0]/(batch_size))

In [12]:
accuracy, errors = data.test_accuracy(predictions, data.x_validate, data.x_other_features_validate, data.y_validate, dictionary, feature_dictionary, vowels)

In [18]:
errors

[[33994, 'adamovega', 'Aspnsg-', 'adámovega', 'ádamovega'],
 [7182, 'adamovem', 'Aspnsl-', 'adámovem', 'ádamovem'],
 [18764, 'adamovemu', 'Aspnsd-', 'adámovemu', 'ádamovemu'],
 [25599, 'adamovim', 'Aspnsi-', 'adámovim', 'ádamovim'],
 [37104, 'adamovo', 'Aspnsn-', 'adámovo', 'ádamovo'],
 [43994, 'adamovo', 'Aspnsa-', 'adámovo', 'ádamovo'],
 [20031, 'algastemu', 'Agpmsd-', 'álgástemu', 'álgastemu'],
 [39855, 'alkoholika', 'Ncmsay', 'alkóhólika', 'alkohólika'],
 [23437, 'alkoholikov', 'Ncmpg-', 'alkoholikov', 'alkohólikov'],
 [35909, 'alkoholikov', 'Ncmdg-', 'alkoholikov', 'alkohólikov'],
 [5063, 'amater', 'Ncmsn-', 'amáter', 'amatér'],
 [4727, 'amaterja', 'Ncmsg-', 'amáterja', 'amatérja'],
 [7503, 'amaterja', 'Ncmda-', 'amáterja', 'amatérja'],
 [20420, 'amaterja', 'Ncmsay', 'amáterja', 'amatérja'],
 [42093, 'amaterja', 'Ncmdn-', 'amáterja', 'amatérja'],
 [52119, 'amaterje', 'Ncmpa-', 'amáterje', 'amatérje'],
 [5484, 'amaterjem', 'Ncmpd-', 'amáterjem', 'amatérjem'],
 [7576, 'amaterjem', '

In [17]:
errors.sort(key=lambda x: x[1])

In [15]:
errors = [[el[0], el[1][::-1], el[2], el[3][::-1], el[4][::-1]] for el in errors]